Avances en el acceso según el rol del usuario
JRS-Developer/pf-server pull request #33
Opened 2021-12-12 15:49 UTC by NLiasso

Estoy trabajando en las autorizaciones. Voy pasando esto para que sigan avanzando los demás. Luego voy a continuar cuando coincidamos en el tipo de acceso requerido por cada acción/ruta

2021-12-12 16:00 UTC, JRS-Developer requested changes

2021-12-12 16:00 UTC, JRS-Developer commented on src/middlewares/auth.js
> +    const sUser = await Role.findAll({where: {name: 'sUser'}})
Si ya no se va a usar, es mejor eliminarlo
```suggestion
```

2021-12-12 16:00 UTC, JRS-Developer commented on src/middlewares/auth.js
> +      return res.status(403).json({ error: 'A JWT token is required' })
Esto ya lo hace la funcion verifyToken, asi que no es necesario hacer la comprobacion.
```suggestion
```

2021-12-12 16:00 UTC, JRS-Developer commented on src/middlewares/auth.js
> +    const tokenDesencriptado = jwt.verify(token, secret)
Si necesitas el role, se puede pasar el role por variables en res.locals y asi usarlo.

2021-12-12 16:00 UTC, JRS-Developer commented on src/middlewares/auth.js
> +    const tokenDesencriptado = jwt.verify(token, secret)
Aqui lo mismo, usar res.locals y ya.

2021-12-15 15:46 UTC, NLiasso reviewed
Es un pull viejo

2021-12-15 16:24 UTC, LeandroVillafuerte approved these changes

2021-12-15 16:26 UTC, NLiasso reviewed
Codigo refactorizado que se verá en el nuevo pull

2021-12-15 16:30 UTC, JRS-Developer approved these changes

2021-12-15 18:08 UTC, merged